# To deploy locally:
# bundle; bundle update; bundle exec jekyll build
# bundle exec jekyll serve
# Configuration: https://mmistakes.github.io/minimal-mistakes/docs/configuration/

title         : Juan José++
subtitle      : Juan José Castellanos
url           : "https://spjuanjoc.github.io"
baseurl       : ""
lang          : es
locale        : es-CO
encoding      : "utf-8"
copyright     : copyright
repository    : "spjuanjoc/spjuanjoc.github.io"
description   : >-
  description
tagline       : >-
  tag line

keywords      : []

# Author
# ==============================================================================
github_username: spjuanjoc
author:
  name        : "Juan José Castellanos"
  avatar      : "/assets/images/bio-photo.jpg"
  bio         : "Ingeniero de Software. Entusiasta de C++."
  links:
    - label   : "GitHub"
      icon    : "fab fa-fw fa-github"
      url     : "https://github.com/spjuanjoc"

footer:
  links:
    - label   : "GitHub"
      icon    : "fab fa-fw fa-github"
      url     : "https://github.com/spjuanjoc"

# Build settings
# ==============================================================================
search                : false
remote_theme          : "mmistakes/minimal-mistakes@4.20.2"
minimal_mistakes_skin : "dark"

# Plugins
# ==============================================================================
plugins:
#  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Conversion
# ==============================================================================
markdown          : kramdown
highlighter       : rouge
incremental       : false
links             : false
excerpt_separator : "\n\n"

# Pagination to skip .../yyyy/mm/dd/...
# ==============================================================================
permalink         : /:categories/:title/
paginate          : 5 # amount of posts to show
paginate_path     : /page:num/
timezone          : America/Bogota # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Include
# ==============================================================================
include:
  - _pages

# Defaults
# ==============================================================================
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout        : single
      author_profile: false
      read_time     : true
      comments      : true
      share         : true
      related       : true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout        : single
      author_profile: true
      related       : false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
