# bundle update
# bundle exec jekyll build
# bundle exec jekyll serve --incremental

url:      "https://spjuanjoc.github.io/" 
baseurl:  ""

lang: es
encoding: "utf-8"

title: spjuanjoc.github.io

description: >- # this means to ignore newlines until "baseurl:"
  description

tagline: >-
  tag line

keywords: []

# ==============================================================================
author:
  name: nombre autor
  email: correo@electronico.com

# Customization
# =============================================================================

# Sidebar image and theme color of the site.
#accent_image:          /assets/img/sidebar-bg.jpg
accent_image:
    background: '#202020'
    overlay: false
##accent_color:          '#4fb1ba'
accent_color:          '#268bd2'

# Build settings
# ==============================================================================
#theme: minima
#theme: jekyll-theme-slate
theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "dark" #"dark"

# Plugins
# ==============================================================================
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Conversion
# ==============================================================================
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Pagination to skip .../yyyy/mm/dd/...
# ==============================================================================
#permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Defaults
# ==============================================================================
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true